/**
 * Signal detection helpers for AI Signal Clarity.
 */

import { classifyStringLiteral, StringCategory } from './string-classifier';

export const AMBIGUOUS_NAME_PATTERNS = [
  /^[a-ce-hj-z]$/, // single letter except d, i, s (common/accepted)
  /^(tmp|temp|data|obj|val|res|ret|elem|thing|stuff|info|misc|util|helper|fn|func)$/i, // Removed 'result', 'cb', 'item', 'handler'
  /^[a-rt-z]\d+$/, // x1, x2, n3 (except s3)
];

export const MAGIC_LITERAL_IGNORE = new Set([
  0, 1, -1, 2, 3, 4, 5, 7, 8, 10, 12, 14, 16, 18, 24, 30, 32, 60, 64, 80, 100,
  128, 192, 200, 201, 204, 256, 365, 400, 401, 403, 404, 429, 443, 500, 503,
  512, 630, 800, 1000, 1024, 1200, 2048, 3000, 8000, 8080,
]);
export const MAGIC_STRING_IGNORE = new Set([
  '',
  ' ',
  '\n',
  '\t',
  'utf8',
  'utf-8',
  'hex',
  'base64',
  'true',
  'false',
  'null',
  'undefined',
  'node',
  'production',
  'development',
  'test',
  'error',
  'warn',
  'info',
  'debug',
  'main',
  'module',
  'types',
  'scripts',
  'dependencies',
  'devDependencies',
  'peerDependencies',
  'remove',
  'delete',
  'update',
  'create',
  'string',
  'number',
  'boolean',
  'object',
  'array',
  'key',
  'id',
  'name',
  'type',
  'value',
  'version',
  'description',
  'timestamp',
  'date',
  'time',
  'status',
  'mode',
  'action',
  'effect',
  'resource',
  'principal',
  'statement',
  'sid',
  'allow',
  'deny',
  'sts:AssumeRole',
  'iam:PassRole',
  's3:GetObject',
  's3:PutObject',
  's3:DeleteObject',
  's3:ListBucket',
  'events:PutEvents',
  'logs:GetLogEvents',
  'sqs:SendMessage',
  'sqs:ReceiveMessage',
  'dynamodb:GetItem',
  'dynamodb:PutItem',
  'dynamodb:UpdateItem',
  'dynamodb:DeleteItem',
  'dynamodb:Query',
  'dynamodb:Scan',
  'critical',
  'major',
  'minor',
  'info',
  'patterns',
  'context',
  'consistency',
  'fragmentation',
  'grounding',
  'testability',
  'deps',
  'contract',
  'compliance',
  'risk',
  // CSS properties and values (Issue: Context-Blind CSS analysis)
  'flex',
  'column',
  'row',
  'relative',
  'absolute',
  'fixed',
  'sticky',
  'static',
  'block',
  'inline',
  'inline-block',
  'grid',
  'none',
  'auto',
  'inherit',
  'initial',
  'unset',
  'nowrap',
  'wrap',
  'space-between',
  'space-around',
  'space-evenly',
  'center',
  'flex-start',
  'flex-end',
  'stretch',
  'baseline',
  'normal',
  'visible',
  'hidden',
  'scroll',
  'auto',
  'repeat',
  'no-repeat',
  'cover',
  'contain',
  'pointer',
  'default',
  'solid',
  'dashed',
  'dotted',
  'transparent',
  'currentColor',
  // Next.js & SEO (Issue: Metadata / Protocol specific strings)
  'en_au',
  'en_us',
  'zh_cn',
  'website',
  'summary_large_image',
  'summary',
  'viewport',
  'charset',
  'canonical',
  'robots',
  'googlebot',
  'all',
  'index',
  'follow',
  'noindex',
  'nofollow',
  'og:title',
  'og:description',
  'og:image',
  'og:url',
  'og:site_name',
  'og:type',
  'twitter:card',
  'twitter:site',
  'twitter:creator',
  'twitter:title',
  'twitter:description',
  'twitter:image',
  // Tool Configs (Issue: Environment/Dev DSL strings)
  'chromium',
  'firefox',
  'webkit',
  'nodejs',
  'aws',
  'lambda',
  'sst',
  'vercel',
  'netlify',
  'github',
  'gitlab',
  'bitbucket',
  // Framework names (Issue 1: Context-Blind String Analysis)
  'sst',
  'react',
  'next',
  'vue',
  'angular',
  'svelte',
  'nuxt',
  'gatsby',
  'remix',
  'astro',
  'vite',
  'webpack',
  'rollup',
  'esbuild',
  'turbo',
  'nx',
  'lerna',
  'pnpm',
  'yarn',
  'npm',
  'jest',
  'vitest',
  'mocha',
  'cypress',
  'playwright',
  'eslint',
  'prettier',
  'typescript',
  'javascript',
  'python',
  'java',
  'go',
  'rust',
  'ruby',
  'php',
  'zod',
  'dotenv',
  'fs',
  'path',
  'child_process',
  'util',
  'uuid',
  // Next.js directive
  'use client',
  'use server',
  // MIME types (Issue 1: Context-Blind String Analysis)
  'text',
  'application',
  'image',
  'audio',
  'video',
  'font',
  'multipart',
  'message',
  'model',
  'example',
  'chemical',
  // Standard MIME type values
  'text/plain',
  'text/html',
  'text/css',
  'text/javascript',
  'text/xml',
  'text/csv',
  'text/markdown',
  'application/json',
  'application/xml',
  'application/javascript',
  'application/octet-stream',
  'application/pdf',
  'application/zip',
  'application/x-www-form-urlencoded',
  'multipart/form-data',
  'image/png',
  'image/jpeg',
  'image/gif',
  'image/svg+xml',
  'image/webp',
  'audio/mpeg',
  'audio/ogg',
  'video/mp4',
  'video/webm',
  // TypeScript/JavaScript keywords (Issue 1: Context-Blind String Analysis)
  'unknown',
  'any',
  'void',
  'never',
  'readonly',
  'abstract',
  'async',
  'await',
  'static',
  'public',
  'private',
  'protected',
  'interface',
  'enum',
  'namespace',
  'module',
  'declare',
  'export',
  'import',
  'extends',
  'implements',
  'constructor',
  'get',
  'set',
  'super',
  'this',
  'typeof',
  'instanceof',
  'in',
  'of',
  'as',
  'is',
  'keyof',
  'infer',
  'unique',
  'symbol',
  'bigint',
  'Promise',
  'Array',
  'Object',
  'String',
  'Number',
  'Boolean',
  'Function',
  'Map',
  'Set',
  'WeakMap',
  'WeakSet',
  'Date',
  'RegExp',
  'Error',
  'JSON',
  'Math',
  'console',
  'process',
  'global',
  'window',
  'document',
  // HTTP methods (Issue 1: Context-Blind String Analysis)
  'GET',
  'POST',
  'PUT',
  'DELETE',
  'PATCH',
  'HEAD',
  'OPTIONS',
  'CONNECT',
  'TRACE',
  // Common HTTP headers
  'Authorization',
  'Content-Type',
  'Accept',
  'User-Agent',
  'Host',
  'Connection',
  'Cache-Control',
  'ETag',
  'Last-Modified',
  'Location',
  'Set-Cookie',
  'Cookie',
  'Referer',
  'Origin',
  // AWS Lambda handler convention (Issue 2: Framework Convention Blindness)
  'handler',
  // Common programming terms (Issue 5: Domain Vocabulary Awareness)
  'config',
  'configuration',
  'options',
  'params',
  'parameters',
  'args',
  'arguments',
  'input',
  'output',
  'result',
  'response',
  'request',
  'data',
  'payload',
  'body',
  'content',
  'message',
  'event',
  'callback',
  'error',
  'exception',
  'success',
  'failure',
  'timeout',
  'retry',
  'attempt',
  'count',
  'index',
  'offset',
  'limit',
  'size',
  'length',
  'width',
  'height',
  'depth',
  'color',
  'background',
  'foreground',
  'border',
  'margin',
  'padding',
  'position',
  'top',
  'bottom',
  'left',
  'right',
  'center',
  'start',
  'end',
  'begin',
  'finish',
  'complete',
  'pending',
  'active',
  'inactive',
  'enabled',
  'disabled',
  'visible',
  'hidden',
  'open',
  'closed',
  'locked',
  'unlocked',
  'read',
  'write',
  'append',
  'prepend',
  'insert',
  'replace',
  'merge',
  'split',
  'join',
  'filter',
  'map',
  'reduce',
  'find',
  'sort',
  'reverse',
  'unique',
  'flatten',
  'compact',
  'chunk',
  'zip',
  'unzip',
  // Statuses (Category 4)
  'completed',
  'failed',
  'unknown',
  'healthy',
  'closed',
  'high',
  'medium',
  'low',
  'success',
  'pending',
  'running',
  'stopped',
]);

const TAILWIND_PATTERN = /^[a-z0-9:-]+(\/[0-9]+)?$/;
// PascalCase or camelCase with at least 2 words is descriptive enough for AI
const DESCRIPTIVE_NAME_PATTERN =
  /^([A-Z]+[a-z0-9]*){2,}$|^([a-z]+[a-z0-9]*)([A-Z]+[a-z0-9]*)+$/;

export function isAmbiguousName(name: string): boolean {
  return AMBIGUOUS_NAME_PATTERNS.some((p) => p.test(name));
}

export function isMagicNumber(value: number): boolean {
  return !MAGIC_LITERAL_IGNORE.has(value);
}

export function isMagicString(value: string): boolean {
  if (value.length === 0) return false;
  if (value.length > 20) return false;
  if (MAGIC_STRING_IGNORE.has(value.toLowerCase())) return false;

  if (TAILWIND_PATTERN.test(value) && value.includes('-')) return false;
  if (/^(gpt|claude|gemini|llama|mixtral|anthropic|openai)-/i.test(value))
    return false;
  if (/^(rate|cron)\(.+\)$/.test(value)) return false; // AWS EventBridge expressions
  if (value === value.toUpperCase() && value.length > 3) return false;
  if (DESCRIPTIVE_NAME_PATTERN.test(value)) return false;
  if (/[/.]/.test(value)) return false;
  if (/^#[0-9a-fA-F]{3,6}$/.test(value)) return false;
  if (/^-?\d+(\.\d+)?(px|rem|em|%|vh|vw|ms|s|deg)$/.test(value)) return false; // CSS units
  if (/^[a-z]{2}([-_][A-Z]{2})?$/.test(value)) return false; // Locales like "en" or "en_US"

  // Use the classifier to distinguish between meaningful and UI strings
  const category = classifyStringLiteral(value);
  // Only flag meaningful strings as magic literals, not UI display strings
  if (category === StringCategory.UiDisplay) {
    return false;
  }

  return !/^\s+$/.test(value);
}

export function isRedundantTypeConstant(name: string, value: any): boolean {
  if (typeof value !== 'string') return false;

  const typeMap: Record<string, string> = {
    TYPE_STRING: 'string',
    TYPE_OBJECT: 'object',
    TYPE_ARRAY: 'array',
    TYPE_NUMBER: 'number',
    TYPE_BOOLEAN: 'boolean',
    TYPE_INTEGER: 'integer',
  };

  // Check for exact matches first
  if (typeMap[name] === value) return true;

  // Check for prefix matches e.g. JSON_TYPE_STRING = 'string'
  for (const [key, val] of Object.entries(typeMap)) {
    if (name.endsWith(key) && value === val) return true;
  }

  return false;
}
